#--------------------- Install config -------------------------#
if(NOT DEFINED INSTALL_CONFIG)
        set(INSTALL_CONFIG "Release")
endif()

IF(WIN32)
install(TARGETS 
        dlEngine

        RUNTIME DESTINATION bin
        PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)

install(FILES
        ${COMPILE_OUTPUT_FOLDER}/${INSTALL_CONFIG}/spdlog.dll
        ${COMPILE_OUTPUT_FOLDER}/${INSTALL_CONFIG}/fmt.dll
        ${COMPILE_OUTPUT_FOLDER}/${INSTALL_CONFIG}/glfw3.dll
        ${COMPILE_OUTPUT_FOLDER}/${INSTALL_CONFIG}/assimp-vc143-mt.dll
        ${COMPILE_OUTPUT_FOLDER}/${INSTALL_CONFIG}/pugixml.dll
        ${COMPILE_OUTPUT_FOLDER}/${INSTALL_CONFIG}/zlib1.dll
        ${COMPILE_OUTPUT_FOLDER}/${INSTALL_CONFIG}/poly2tri.dll
        ${COMPILE_OUTPUT_FOLDER}/${INSTALL_CONFIG}/minizip.dll
        ${COMPILE_OUTPUT_FOLDER}/${INSTALL_CONFIG}/kubazip.dll

        DESTINATION bin
        PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)

ELSEIF(UNIX)
install(TARGETS
        dlEngine

        LIBRARY DESTINATION bin
        PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)

ENDIF()

install(TARGETS dlSandbox 
        RUNTIME DESTINATION bin
        PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)

install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/runtime/config/keybinds.ini
        DESTINATION ./config/)

install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/version.txt
        DESTINATION .)

install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/runtime/shader DESTINATION .

        PATTERN "cache" EXCLUDE
        PATTERN ${CMAKE_CURRENT_SOURCE_DIR}/runtime/shader

        PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
)

install(DIRECTORY
        ${CMAKE_CURRENT_SOURCE_DIR}/runtime/asset
        DESTINATION .
        )