name: Windows-Release

on:
  workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        cd ThirdParty/vcpkg/
        .\bootstrap-vcpkg.bat
        .\vcpkg.exe install --triplet=x64-windows --overlay-triplets=ThirdParty\vcpkg_triplets\

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DVCPKG_TARGET_TRIPLET=x64-windows

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Install
      run: cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}/install

    - name: Pack Installer
      run: |
        $VersionNumber = powershell -ExecutionPolicy Bypass -File WinScripts/GetVersionNumber.ps1
        $ProductName = "Daedalus Development Sandbox-" + $VersionNumber + "-win64"
        $ProductPath = "${{github.workspace}}/install/" + $ProductName + ".exe"
        Write-Host "ProductName: $ProductName"
        Write-Host "ProductPath: $ProductPath"
        Write-Host "VersionNumber: $VersionNumber"
        Write-Output "##vso[task.setvariable variable=ProductName]$ProductName"
        Write-Output "##vso[task.setvariable variable=ProductPath]$ProductPath"
        Write-Output "##vso[task.setvariable variable=ProductPath]$ProductPath"

        cd build
        cpack

    - uses: djnicholson/release-action@v2.11
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-name: "Daedalus Development Sandbox"
        tag-name: 'v0.1.2'
        asset-name: 'Daedalus Development Sandbox-0.1.2-win64.exe'
        file: '${{github.workspace}}/install/Daedalus Development Sandbox-0.1.2-win64.exe'