name: Windows-Release

on:
  workflow_dispatch

env:
  BUILD_TYPE: Release
  PRODUCT_VERSION: '0.0.0'
  PRODUCT_NAME: 'Daedalus Development Sandbox'

jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        cd WinScripts
        ./InstallVCPKG.ps1

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DVCPKG_TARGET_TRIPLET=x64-windows

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Install
      run: cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}/install

    - name: Pack Installer
      run: |
        $VersionNumber = powershell -ExecutionPolicy Bypass -File WinScripts/GetVersionNumber.ps1
        $ProductName = "Daedalus Development Sandbox-" + $VersionNumber + "-win64"
        Write-Host "Product Version: $VersionNumber"
        Write-Host "Product Name: $ProductName"
        echo "PRODUCT_VERSION=$(VersionNumber)" >> $GITHUB_ENV
        echo "PRODUCT_NAME=$(VersionNumber)" >> $GITHUB_ENV

        cd build
        cpack

    - uses: djnicholson/release-action@v2.11
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-name: '$(env.PRODUCT_NAME)'
        tag-name: '$(env.PRODUCT_VERSION)'
        asset-name: '$(env.PRODUCT_NAME).exe'
        file: '${{github.workspace}}/install/$(env.PRODUCT_NAME).exe'