name: Windows-Dev-CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        cd ThirdParty/vcpkg/
        .\bootstrap-vcpkg.bat
        .\vcpkg.exe install --triplet=x64-windows --overlay-triplets=ThirdParty\vcpkg_triplets\

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_TESTS=ON -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/ThirdParty/vcpkg/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}  -VV
